version: '3.6'

services: 

   db:
     image: mysql:8.0.31
     restart: always
     volumes:
      - ./db:/var/lib/mysql   
     command: mysqld --default_authentication_plugin=mysql_native_password
     environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD 
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
     ports:
      - 3308:3306
     networks:
      - network-docker

   wordpress:
     image: wordpress:6.0.2
     restart: always
     volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html
     ports:
      - 8080:80
     depends_on:
      - db
     environment:
      TZ: America/Sao_Paulo
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
     networks:
      - network-docker
   
networks:
     network-docker:
      driver: bridge 
